In [1]:
import numpy as np

```python
arange([start,] stop[, step,], dtype=None)
```

- 지정한 범위에 해당하는 데이터를 생성
- start: 시작값
- stop: 종료값
- step: 간격
- dtype: 데이터 타입


In [2]:
a = np.arange(15)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


```python
reshape(a, newshape)
```

- 데이터를 지정한 모양으로 변형
- a: 데이터
- newshape: 변형할 모양


In [3]:
b = a.reshape(3, 5)

print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


```python
zeros(shape, dtype=float)
```

- 지정한 모양에 해당하는 데이터를 0으로 채움
- shape: 모양
- dtype: 데이터 타입


In [4]:
c = np.zeros((3, 4), dtype=int)

print(c)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


```python
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
```

- 데이터를 배열로 변환
- object: 데이터
- dtype: 데이터 타입
- copy: 복사 여부
- order: 배열 순서
- subok: 하위 클래스 여부
- ndmin: 최소 차원

In [5]:
plist1 = [1, 2, 3]
plist2 = [4, 5, 6]

arr1 = np.array(plist1)
arr2 = np.array(plist2)

In [6]:
plist3 = []

for i in range(len(plist1)):
    plist3.append(plist1[i] + 1)

print(plist3)
print(arr1 + 1)

plist1 + [1]

[2, 3, 4]
[2 3 4]


[1, 2, 3, 1]

In [7]:
print(plist1 * 2)
print(arr1 * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [8]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [9]:
a[0, 0]

1

In [10]:
a[1, 1]

6

In [11]:
a[2, 3]

11